LEX_KEYWORDS = {
            "new": "DECLARATION",
            "func": "FUNCTION",
            "+": "PLUS",
            "-": "MINUS",
            "/": "DIVIDE",
            "*": "MULTIPLY",
            "=": "ASSIGNMENT",
            ";": "BREAK",
            "for": "FOR",
            "while": "WHILE",
            "pass": "PASS",
            "end": "END",
            "if": "IF",
            "else": "ELSE",
            "else if": "ELSEIF",
            "<": "LESSTHAN",
            ">": "GREATERTHAN",
            "<=": "LESSEQUALS",
            ">=": "GREATEQUALS",
            "==": "EQUALS",
            ",": "COMMA",
            "{": "LEFTPAREN",
            "}": "RIGHTPAREN",
            "(": "LEFTBRACKETS",
            ")": "RIGHTBRACKETS",
        }